version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor:
      node/default
    steps:
      - checkout
      - run: npm install
  test:
    executor:
      node/default
    steps:
      - checkout
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - test
